# Nixy listening port
port = "6000"
# X-Proxy header, defaults to hostname
xproxy = ""
# Marathon API
# add all HA cluster nodes in priority order.
marathon = ["http://example01:8080", "http://example02:8080"]
user = "" # leave empty if no auth is required.
pass = ""
# Nginx
nginx_config = "/etc/nginx/nginx.conf"
nginx_template = "/etc/nginx/nginx.tmpl"
nginx_cmd = "nginx" # optionally "openresty" or "docker exec nginx nginx"
# Statsd settings
[statsd]
addr = "localhost:8125" # optional for statistics
#namespace = "nixy.my_mesos_cluster"
#sample_rate = 100